export const ACTIVE_PLAYER_BOARD_COLOR = "#D4AFC3";
export const INACTIVE_PLAYER_BOARD_COLOR = "#BF7991";

export const ACTIVE_PLAYER_CURRENT_SCORE_BG_COLOR = "#C7365F";
export const INACTIVE_PLAYER_CURRENT_SCORE_BG_COLOR = "#C4436B";

export const ACTIVE_CURRENT_SCORE_COLOR = "#FFFFFF";
export const INACTIVE_CURRENT_SCORE_COLOR = "#EFE4EC";

export const WIN_SCORE = 50;
